-- MySQL Script generated by MySQL Workbench
-- Mon Jul  4 11:30:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Domgames
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema Domgames
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Domgames` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Domgames` ;

-- -----------------------------------------------------
-- Table `Domgames`.`enderecos_res`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`enderecos_res` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `referencia` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `pais` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`enderecos_ens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`enderecos_ens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `referencia` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `pais` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`formas_pgtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`formas_pgtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cartao_1` VARCHAR(18) NULL,
  `cartao_2` VARCHAR(18) NULL,
  `cartao_3` VARCHAR(18) NULL,
  `banco_transferencia` VARCHAR(18) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `Domgames`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  `birthday` DATE NOT NULL,
  `gender` TINYINT(3) NULL DEFAULT 3,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(11) NOT NULL,
  `cel_whats` VARCHAR(15) NOT NULL,
  `tel` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) GENERATED ALWAYS AS () VIRTUAL,
  `password` VARCHAR(25) NOT NULL,
  `enderecos_res_id` INT NOT NULL,
  `enderecos_ens_id` INT NOT NULL,
  `formas_pgtos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_usuarios_enderecos_res1_idx` (`enderecos_res_id` ASC),
  INDEX `fk_usuarios_enderecos_ens1_idx` (`enderecos_ens_id` ASC),
  INDEX `fk_usuarios_formas_pgtos1_idx` (`formas_pgtos_id` ASC),
  CONSTRAINT `fk_usuarios_enderecos_res1`
    FOREIGN KEY (`enderecos_res_id`)
    REFERENCES `Domgames`.`enderecos_res` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_enderecos_ens1`
    FOREIGN KEY (`enderecos_ens_id`)
    REFERENCES `Domgames`.`enderecos_ens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_formas_pgtos1`
    FOREIGN KEY (`formas_pgtos_id`)
    REFERENCES `Domgames`.`formas_pgtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`historicos_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`historicos_compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nota_fiscal` VARCHAR(300) NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historicos_compras_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_historicos_compras_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Domgames`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `Domgames`.`assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`assets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao_interna` LONGTEXT NULL,
  `descricao_externa` VARCHAR(45) NULL,
  `image` VARCHAR(200) NULL,
  `image_externa` VARCHAR(45) NULL,
  `video_youtube` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`fabricantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`fabricantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fabricante` VARCHAR(45) NOT NULL,
  `assets_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`fabricante` ASC),
  INDEX `fk_fabricantes_assets1_idx` (`assets_id` ASC),
  CONSTRAINT `fk_fabricantes_assets1`
    FOREIGN KEY (`assets_id`)
    REFERENCES `Domgames`.`assets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`plataformas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`plataformas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `estoque` MEDIUMINT NULL,
  `promocao` TINYINT(1) NULL DEFAULT 0,
  `novo_usado` TINYINT(1) NOT NULL DEFAULT 0,
  `assets_id` INT NOT NULL,
  `fabricantes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_plataformas_assets1_idx` (`assets_id` ASC),
  INDEX `fk_plataformas_fabricantes1_idx` (`fabricantes_id` ASC),
  CONSTRAINT `fk_plataformas_assets1`
    FOREIGN KEY (`assets_id`)
    REFERENCES `Domgames`.`assets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plataformas_fabricantes1`
    FOREIGN KEY (`fabricantes_id`)
    REFERENCES `Domgames`.`fabricantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`acessorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`acessorios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `estoque` MEDIUMINT NULL,
  `promocao` TINYINT(1) NULL DEFAULT 0,
  `novo_usado` TINYINT(1) NOT NULL DEFAULT 0,
  `assets_id` INT NOT NULL,
  `fabricantes_id` INT NOT NULL,
  `plataformas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_ACESSORIOS_DESCRICAO1_idx` (`assets_id` ASC),
  INDEX `fk_ACESSORIOS_FABRICANTE1_idx` (`fabricantes_id` ASC),
  INDEX `fk_ACESSORIOS_PLATAFORMA1_idx` (`plataformas_id` ASC),
  CONSTRAINT `fk_ACESSORIOS_DESCRICAO1`
    FOREIGN KEY (`assets_id`)
    REFERENCES `Domgames`.`assets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACESSORIOS_FABRICANTE1`
    FOREIGN KEY (`fabricantes_id`)
    REFERENCES `Domgames`.`fabricantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACESSORIOS_PLATAFORMA1`
    FOREIGN KEY (`plataformas_id`)
    REFERENCES `Domgames`.`plataformas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`jogos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `estoque` MEDIUMINT NOT NULL,
  `chave` VARCHAR(100) NULL,
  `midia_fisica` TINYINT(1) NULL DEFAULT 0,
  `promocao` TINYINT(1) NULL DEFAULT 0,
  `novo_usado` TINYINT(1) NOT NULL DEFAULT 0,
  `genero` VARCHAR(45) NULL,
  `plataformas_id` INT NOT NULL,
  `assets_id` INT NOT NULL,
  `fabricantes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_jogos_plataformas1_idx` (`plataformas_id` ASC),
  INDEX `fk_jogos_assets1_idx` (`assets_id` ASC),
  INDEX `fk_jogos_fabricantes1_idx` (`fabricantes_id` ASC),
  CONSTRAINT `fk_jogos_plataformas1`
    FOREIGN KEY (`plataformas_id`)
    REFERENCES `Domgames`.`plataformas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_assets1`
    FOREIGN KEY (`assets_id`)
    REFERENCES `Domgames`.`assets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_fabricantes1`
    FOREIGN KEY (`fabricantes_id`)
    REFERENCES `Domgames`.`fabricantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`giftcards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`giftcards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `estoque` MEDIUMINT NULL,
  `promocao` TINYINT(1) NULL DEFAULT 0,
  `chave` VARCHAR(100) NULL,
  `assets_id` INT NOT NULL,
  `fabricantes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_GIFTCARDS_DESCRICAO1_idx` (`assets_id` ASC),
  INDEX `fk_GIFTCARDS_FABRICANTE1_idx` (`fabricantes_id` ASC),
  UNIQUE INDEX `chave_UNIQUE` (`chave` ASC),
  CONSTRAINT `fk_GIFTCARDS_DESCRICAO1`
    FOREIGN KEY (`assets_id`)
    REFERENCES `Domgames`.`assets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GIFTCARDS_FABRICANTE1`
    FOREIGN KEY (`fabricantes_id`)
    REFERENCES `Domgames`.`fabricantes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plataformas_id` INT NOT NULL,
  `acessorios_id` INT NOT NULL,
  `jogos_id` INT NOT NULL,
  `giftcards_id` INT NOT NULL,
  `preco_promocional` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_plataformas1_idx` (`plataformas_id` ASC),
  INDEX `fk_produtos_acessorios1_idx` (`acessorios_id` ASC),
  INDEX `fk_produtos_jogos1_idx` (`jogos_id` ASC),
  INDEX `fk_produtos_giftcards1_idx` (`giftcards_id` ASC),
  CONSTRAINT `fk_produtos_plataformas1`
    FOREIGN KEY (`plataformas_id`)
    REFERENCES `Domgames`.`plataformas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_acessorios1`
    FOREIGN KEY (`acessorios_id`)
    REFERENCES `Domgames`.`acessorios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_jogos1`
    FOREIGN KEY (`jogos_id`)
    REFERENCES `Domgames`.`jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_giftcards1`
    FOREIGN KEY (`giftcards_id`)
    REFERENCES `Domgames`.`giftcards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produtos_id` INT NOT NULL,
  `preco_total` DECIMAL NULL,
  `tipo_pgto` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendas_produtos1_idx` (`produtos_id` ASC),
  CONSTRAINT `fk_vendas_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `Domgames`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Domgames`.`email_disparo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`email_disparo` (
  `id` INT NOT NULL,
  `email_disparo` VARCHAR(100) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `produtos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_disparo_UNIQUE` (`email_disparo` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_email_disparo_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_email_disparo_produtos1_idx` (`produtos_id` ASC),
  CONSTRAINT `fk_email_disparo_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Domgames`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_disparo_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `Domgames`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `Domgames`.`historicos_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Domgames`.`historicos_vendas` (
  `historicos_compras_id` INT NOT NULL,
  `vendas_id` INT NOT NULL,
  PRIMARY KEY (`historicos_compras_id`, `vendas_id`),
  INDEX `fk_historicos_compras_has_vendas_vendas1_idx` (`vendas_id` ASC),
  INDEX `fk_historicos_compras_has_vendas_historicos_compras1_idx` (`historicos_compras_id` ASC),
  CONSTRAINT `fk_historicos_compras_has_vendas_historicos_compras1`
    FOREIGN KEY (`historicos_compras_id`)
    REFERENCES `Domgames`.`historicos_compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historicos_compras_has_vendas_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `Domgames`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
